layout_spectrum: 1
typography_spectrum: 0.8960574
color:
  saturation: 0.2905075
  lightness: 0.9424011
  brandStrength: 0.6376773
  rhythmicContrast: 0.8528249
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: SeanARowe
